name: push-master-to-staging

on:
  push:
    branches:
      - 'master'

jobs:
  push-master-to-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git checkout staging
          git merge origin/master
          git push origin staging
